import {render,screen,within,fireEvent,waitFor} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {describe,it,expect,vi,beforeEach} from "vitest";import PortfolioSite from "./PortfolioSite";import {contactHref} from "@/config/contact";
beforeEach(()=>{vi.clearAllMocks()});
describe("portfolio",()=>{
 it("renders hero and pricing content",()=>{render(<PortfolioSite/>);expect(screen.getByRole("heading",{name:/Nowoczesna strona/})).toBeInTheDocument();expect(screen.getByText("1 000 PLN")).toBeInTheDocument();expect(screen.getByText("od 2 500 PLN")).toBeInTheDocument()});
 it("navigation points to real sections and external links are safe",()=>{render(<PortfolioSite/>);expect(screen.getAllByRole("link",{name:"Realizacje"})[0]).toHaveAttribute("href","#portfolio");for(const link of screen.getAllByRole("link").filter(x=>x.getAttribute("target")==="_blank"))expect(link).toHaveAttribute("rel","noopener noreferrer")});
 it("filters portfolio",async()=>{render(<PortfolioSite/>);await userEvent.click(screen.getAllByRole("button",{name:"Motoryzacja"})[0]);expect(screen.getByText("SPECTRE Detailing House")).toBeInTheDocument();expect(screen.queryByText("Vazi — kuchnia gruzińska")).not.toBeInTheDocument()});
 it("opens and closes project modal with Escape",async()=>{render(<PortfolioSite/>);await userEvent.click(screen.getAllByRole("button",{name:/Zobacz zakres/})[0]);expect(screen.getByRole("dialog")).toBeInTheDocument();fireEvent.keyDown(window,{key:"Escape"});await waitFor(()=>expect(screen.queryByRole("dialog")).not.toBeInTheDocument())});
 it("selector supports multi-select and recommends custom",async()=>{render(<PortfolioSite/>);await userEvent.click(screen.getByRole("button",{name:"Kalkulator"}));await userEvent.click(screen.getByRole("button",{name:"Galeria"}));expect(screen.getByText("Projekt indywidualny")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Kalkulator"})).toHaveAttribute("aria-pressed","true")});
 it("copies structured brief",async()=>{render(<PortfolioSite/>);await userEvent.click(screen.getByRole("button",{name:/Skopiuj brief/}));expect(navigator.clipboard.writeText).toHaveBeenCalledWith(expect.stringContaining("Brief projektu strony"));expect(await screen.findByRole("status")).toHaveTextContent("Brief został skopiowany")});
 it("missing contact opens fallback modal",async()=>{render(<PortfolioSite/>);await userEvent.click(screen.getAllByRole("button",{name:/Wyślij zapytanie/})[0]);expect(screen.getByRole("dialog")).toHaveTextContent("Ten kanał kontaktu jest obecnie konfigurowany");expect(within(screen.getByRole("dialog")).getByRole("link",{name:/@ant0niy07/})).toHaveAttribute("href","https://instagram.com/ant0niy07")});
 it("validates contact form without discarding data",async()=>{render(<PortfolioSite/>);const form=screen.getAllByRole("button",{name:/Skopiuj i wyślij/})[0];await userEvent.click(form);expect(screen.getAllByRole("alert").length).toBeGreaterThan(0);const name=screen.getAllByRole("textbox",{name:/Imię/})[0];await userEvent.type(name,"Anna");await userEvent.click(form);expect(name).toHaveValue("Anna")});
 it("FAQ accordion toggles accessibly",async()=>{render(<PortfolioSite/>);const q=screen.getByRole("button",{name:/Czy naprawdę/});expect(q).toHaveAttribute("aria-expanded","true");await userEvent.click(q);expect(q).toHaveAttribute("aria-expanded","false")});
});
describe("configured destinations",()=>{it("builds WhatsApp, tel and email links",()=>{expect(contactHref("whatsapp","+48 500 600 700","Dzień dobry")).toContain("https://wa.me/48500600700?text=");expect(contactHref("phone","+48 500")).toBe("tel:+48500");expect(contactHref("email","a@b.pl","Brief")).toContain("mailto:a@b.pl")});it("returns null for missing contact",()=>expect(contactHref("telegram",null)).toBeNull())});
